# Generated by Django 5.0.6 on 2024-07-28 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='door_pass_through',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='folded_w_wheels',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='folded_wo_wheels',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='frame',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='handle_height_ground_to_handle',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='head_room_inside_canopy',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='seat_back_height',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='stand_up',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_wo_wheels',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='wheels',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.CharField(default='To be announced', max_length=255),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.product'),
        ),
    ]
