# Generated by Django 5.0.6 on 2024-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_color_product_door_pass_through_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='door_pass_through',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='folded_w_wheels',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='folded_wo_wheels',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='handle_height_ground_to_handle',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='head_room_inside_canopy',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='seat_back_height',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stand_up',
            field=models.CharField(blank=True, default='Siuuu', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_wo_wheels',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wheels',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(blank=True, default='To be announced!', max_length=255, null=True),
        ),
    ]
