# Generated by Django 5.0.6 on 2024-08-20 16:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_product_color_alter_product_door_pass_through_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wishlist',
            new_name='wishlist_model',
        ),
    ]
