# Generated by Django 5.1 on 2024-09-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_rename_wishlist_wishlist_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="mobile",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
